# Generated by Django 3.1.1 on 2020-09-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.CharField(default='', max_length=1000)),
                ('country', models.CharField(default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.CharField(default='', max_length=1000)),
                ('country', models.CharField(default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('synopsis', models.TextField(help_text='Synopsis of the movie', max_length=1000)),
                ('cover', models.CharField(default='', max_length=500)),
                ('trailer', models.CharField(default='', max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('running_time', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=300)),
                ('language', models.CharField(default='', max_length=500)),
                ('magnet', models.CharField(default='', max_length=1000)),
                ('cast', models.ManyToManyField(help_text='Select the actors of this movie', to='resources.Actor')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.director')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this game', to='resources.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(default='', max_length=1000)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
